version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
    - "/home/ubuntu/wrkdir/word2vec/word2vec/data:/data:rw"
    ports:
      - "8000:8000"
    networks:
      - default
      - kgprecommenderbackend_default
networks:
  kgprecommenderbackend_default:
    external: true
